#include "\X39_MS2_Scripting\default.hpp"
/*
 *	THIS FUNCTION IS NOT INTENDED TO BE CALLEN BY ANY USERSCRIPT!
 *	
 *	@Return - N/A
 *	@Author - X39|Cpt. HM Murdock
 */
if(!isServer) exitWith {};

["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Legs_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfLegs) / X39_MS2_var_Bleeding_maxBleedingLegs;		(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Legs_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getBleedingOfLegs) / X39_MS2_var_Bleeding_maxBleedingLegs;		(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Legs_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfLegs) / X39_MS2_var_Bleeding_maxBleedingLegs;		(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Legs_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfLegs) / X39_MS2_var_Bleeding_maxBleedingLegs;		(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Hands_Low",		[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHands) / X39_MS2_var_Bleeding_maxBleedingHands;	(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Hands_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getBleedingOfHands) / X39_MS2_var_Bleeding_maxBleedingHands;	(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Hands_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHands) / X39_MS2_var_Bleeding_maxBleedingHands;	(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Hands_Extreme",	[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHands) / X39_MS2_var_Bleeding_maxBleedingHands;	(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Head_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHead) / X39_MS2_var_Bleeding_maxBleedingHead;		(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Head_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getBleedingOfHead) / X39_MS2_var_Bleeding_maxBleedingHead;		(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Head_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHead) / X39_MS2_var_Bleeding_maxBleedingHead;		(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Head_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfHead) / X39_MS2_var_Bleeding_maxBleedingHead;		(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Generic_Low",		[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfGeneric) / X39_MS2_var_Bleeding_maxBleedingGeneric;(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Generic_Middle",	[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getBleedingOfGeneric) / X39_MS2_var_Bleeding_maxBleedingGeneric;(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Generic_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfGeneric) / X39_MS2_var_Bleeding_maxBleedingGeneric;(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Generic_Extreme",	[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfGeneric) / X39_MS2_var_Bleeding_maxBleedingGeneric;(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Body_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfBody) / X39_MS2_var_Bleeding_maxBleedingBody;		(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Body_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getBleedingOfBody) / X39_MS2_var_Bleeding_maxBleedingBody;		(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Body_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfBody) / X39_MS2_var_Bleeding_maxBleedingBody;		(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_Body_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getBleedingOfBody) / X39_MS2_var_Bleeding_maxBleedingBody;		(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;

["STR_X39_MS2_Scripting_MedicalMessages_Damage_Legs_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfLegs) / X39_MS2_var_Damage_maxDamageLegs;			(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Legs_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getDamageOfLegs) / X39_MS2_var_Damage_maxDamageLegs;			(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Legs_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfLegs) / X39_MS2_var_Damage_maxDamageLegs;			(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Legs_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfLegs) / X39_MS2_var_Damage_maxDamageLegs;			(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Hands_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHands) / X39_MS2_var_Damage_maxDamageHands;			(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Hands_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getDamageOfHands) / X39_MS2_var_Damage_maxDamageHands;			(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Hands_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHands) / X39_MS2_var_Damage_maxDamageHands;			(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Hands_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHands) / X39_MS2_var_Damage_maxDamageHands;			(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Head_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHead) / X39_MS2_var_Damage_maxDamageHead;			(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Head_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getDamageOfHead) / X39_MS2_var_Damage_maxDamageHead;			(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Head_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHead) / X39_MS2_var_Damage_maxDamageHead;			(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Head_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfHead) / X39_MS2_var_Damage_maxDamageHead;			(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Generic_Low",		[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfGeneric) / X39_MS2_var_Damage_maxDamageGeneric;		(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Generic_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getDamageOfGeneric) / X39_MS2_var_Damage_maxDamageGeneric;		(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Generic_High",		[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfGeneric) / X39_MS2_var_Damage_maxDamageGeneric;		(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Generic_Extreme",	[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfGeneric) / X39_MS2_var_Damage_maxDamageGeneric;		(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Body_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfBody) / X39_MS2_var_Damage_maxDamageBody;			(_value >= 0.1 && _value < 0.3)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Body_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getDamageOfBody) / X39_MS2_var_Damage_maxDamageBody;			(_value >= 0.3 && _value < 0.6)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Body_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfBody) / X39_MS2_var_Damage_maxDamageBody;			(_value >= 0.6 && _value < 0.7)	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Damage_Body_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getDamageOfBody) / X39_MS2_var_Damage_maxDamageBody;			(_value >= 0.7)					}, 0] call X39_MS2_fnc_registerMedicalMessage;

["STR_X39_MS2_Scripting_MedicalMessages_Pain_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			(!([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.1 && _value < 0.3))	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			(!([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.3 && _value < 0.6))	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			(!([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.6 && _value < 0.7))	}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			(!([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.7))					}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_Low",			[1, 1, 1, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			( ([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.1 && _value < 0.3))	}, 2] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_Middle",		[0.5, 0.5, 0, 1],	{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			( ([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.3 && _value < 0.6))	}, 2] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_High",			[1, 1, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			( ([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.6 && _value < 0.7))	}, 2] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Pain_Extreme",		[1, 0, 0, 1],		{_value = ([_this] call X39_MS2_fnc_getPain) / ([] call X39_MS2_fnc_getMaxPain);			( ([_this] call X39_MS2_fnc_isBlackedOut) && (_value >= 0.7))					}, 2] call X39_MS2_fnc_registerMedicalMessage;

["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_ExcessiveBloodLoss",	[1, 0, 0, 1],		{[_this] call X39_MS2_fnc_getAterialDamage || {((([_this] call X39_MS2_fnc_getBleedingOfLegs) / X39_MS2_var_Bleeding_maxBleedingLegs)			>= 0.7) || {((([_this] call X39_MS2_fnc_getBleedingOfHands) / X39_MS2_var_Bleeding_maxBleedingHands)		>= 0.7) || {((([_this] call X39_MS2_fnc_getBleedingOfHead) / X39_MS2_var_Bleeding_maxBleedingHead)			>= 0.7) || {((([_this] call X39_MS2_fnc_getBleedingOfGeneric) / X39_MS2_var_Bleeding_maxBleedingGeneric)	>= 0.7) || {((([_this] call X39_MS2_fnc_getBleedingOfBody) / X39_MS2_var_Bleeding_maxBleedingBody)			>= 0.7)}}}}}}, 0] call X39_MS2_fnc_registerMedicalMessage;
["STR_X39_MS2_Scripting_MedicalMessages_Bleeding_AterialDamage",		[1, 0, 0, 1],		{[_this] call X39_MS2_fnc_getAterialDamage}, 1] call X39_MS2_fnc_registerMedicalMessage;
[{format[localize "STR_X39_MS2_Scripting_MedicalMessages_Bleeding_BloodPresure", name _this, (([_this] call X39_MS2_fnc_getBlood) / X39_MS2_var_Bleeding_maxBloodInEntireBody) * X39_MS2_var_Bleeding_NaturalMaxOfBloodPresure},		[1, 1, 1, 1],		{true}, 2] call X39_MS2_fnc_registerMedicalMessage;

publicVariable "X39_MS2_var_Internal_MedicalMessages";